/bt_operator:
  ros__parameters:
    # default_bt_xml_filename: "simple_tree.xml"
    # default_plugin_lib_names:
    #   - util_plugin_print_value
    customized_plugin_lib_names:
      man2_bt_skill_clients:
        - detect_aruco_marker_client
        - compute_path_to_state_client
        - compute_path_to_pose_client
        - compute_path_to_point_client
        - execute_trajectory_client
        - set_path_constraints_client
        - get_current_ik_frame_pose_client
        - print_value

/detect_aruco_marker_action_server:
  ros__parameters:
    sub_marker_topic: "/marker"
    required_pose_num: 2
    sub_rate: 10
    timeout: 5000

/moveit_skill_server:
  ros__parameters:
    planning_pipeline: "ompl"
    planner_id: "RRTstarkConfigDefault"
    planning_attempts: 10
    step_size: 0.005
    min_fraction: 0.50
    max_acceleration_scaling_factor: 0.3
    max_velocity_scaling_factor: 0.1
    planning_time: 1.0
