#goal
int32 marker_id
string frame_id
geometry_msgs/PoseStamped container_a
geometry_msgs/PoseStamped container_b
---
#result
geometry_msgs/PoseStamped marker_pose
geometry_msgs/PoseStamped container_pose
---
#feedback