#!/usr/bin/env python
from help_extern_server.server_threading import Help_Server_Node
import rospy

if __name__ == '__main__':
    help_server = Help_Server_Node()
    help_server.help_server_init()
    rate = rospy.Rate(100)
    rospy.spin()